parameters:
    assetic.filter.riot.class: PaulHughes01\Riot\Assetic
    assetic.filter.riot.node: '%assetic.node.bin%'
    assetic.filter.riot.node_paths: '%assetic.node.paths%'

services:
    assetic.filter.riot:
        class: %assetic.filter.riot.class%
        tags:
            - { name: assetic.filter, alias: riot }
        arguments: ['%assetic.filter.riot.node%']
        calls:
            - [setNodePaths, ['%assetic.filter.riot.node_paths%']]

